// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqZu6QVAI9azW2_KzAyAZhHvn329poQhQ',
    appId: '1:280394763264:web:bb4dbfbba35bfa2de21ce5',
    messagingSenderId: '280394763264',
    projectId: 'chat-firebase-723dc',
    authDomain: 'chat-firebase-723dc.firebaseapp.com',
    storageBucket: 'chat-firebase-723dc.appspot.com',
    measurementId: 'G-86NMVY9HD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkQgE-MBpHY2EHEw-qQqVLgHVikdp1e3o',
    appId: '1:280394763264:android:016b8a1b8a6aeb56e21ce5',
    messagingSenderId: '280394763264',
    projectId: 'chat-firebase-723dc',
    storageBucket: 'chat-firebase-723dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBZG6jb30Vbtgh5Qo6O1BFByHlvToDW5E',
    appId: '1:280394763264:ios:4095eae2bfeef3b4e21ce5',
    messagingSenderId: '280394763264',
    projectId: 'chat-firebase-723dc',
    storageBucket: 'chat-firebase-723dc.appspot.com',
    androidClientId: '280394763264-8g9g99f4pak76phgpdsors4f4e8li1tk.apps.googleusercontent.com',
    iosClientId: '280394763264-grvdrsce0uk3i1ctl6e1i8j3af1lkq7g.apps.googleusercontent.com',
    iosBundleId: 'com.humayun.chat.firebase.chatFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBZG6jb30Vbtgh5Qo6O1BFByHlvToDW5E',
    appId: '1:280394763264:ios:4095eae2bfeef3b4e21ce5',
    messagingSenderId: '280394763264',
    projectId: 'chat-firebase-723dc',
    storageBucket: 'chat-firebase-723dc.appspot.com',
    androidClientId: '280394763264-8g9g99f4pak76phgpdsors4f4e8li1tk.apps.googleusercontent.com',
    iosClientId: '280394763264-grvdrsce0uk3i1ctl6e1i8j3af1lkq7g.apps.googleusercontent.com',
    iosBundleId: 'com.humayun.chat.firebase.chatFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqZu6QVAI9azW2_KzAyAZhHvn329poQhQ',
    appId: '1:280394763264:web:aba7b39f4118d539e21ce5',
    messagingSenderId: '280394763264',
    projectId: 'chat-firebase-723dc',
    authDomain: 'chat-firebase-723dc.firebaseapp.com',
    storageBucket: 'chat-firebase-723dc.appspot.com',
    measurementId: 'G-6G3HS05VCX',
  );

}